### ISSUE TITLE
Distribution package don't contain "pyramid_formalchemy/paster_templates" folder :(

### ISSUE THREAD

**Issue by harobed** [FormAlchemy/pyramid_formalchemy#11]
This distribution package don't contain "pyramid_formalchemy/paster_templates" folder :(

http://pypi.python.org/packages/source/p/pyramid_formalchemy/pyramid_formalchemy-0.4.tar.gz

Regards,
Stephane

**Comment by do3cc** [comment]
Creating a new egg with the setuptools_git package installed will do the trick. I just tried it myself and realised that the files won't be added if build with my virtualenv python which did not contain setuptools_git

**Comment by do3cc** [comment]
Fixed with release 0.4.1
