### ISSUE TITLE
pyramid autocomplete renderer - where has it gone?

### ISSUE THREAD

**Issue by ddimmich** [FormAlchemy/pyramid_formalchemy#21]
Hi,

The changelogs indicate that the pyramid autocomplete renderer was moved out of pyramid_formalchemy at some point - but its not clear where it has gone to?  I can't find it in fa.jquery or anywhere else i've looked?

Thanks,
Damian

**Comment by gawel** [comment]
https://github.com/FormAlchemy/fa.jquery/blob/master/fa/jquery/pyramid/renderers.py#L33
